name: "Linter"
on: [push]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1      
      - run: composer install
      - run: php -d memory_limit=-1
      - run: make lint
