name: "Linter"
on: [push]
jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1      
      - run: composer install
      - run: composer exec --verbose phpcs -d memory_limit=200M -- --standard=PSR12 src bin
